consumes:
- application/json
info:
  title: Platfarm Test Project For Github
  version: 0.1.0
paths: {
    /:
    get:
      tags:
        - todos
      parameters:
        - name: since
          in: query
          type: integer
          format: int64
        - name: limit
          in: query
          type: integer
          format: int32
          default: 20
      responses:
        200:
          description: list the todo operations
          schema:
            type: array
            items:
              $ref: "#/definitions/item"
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/error"
}
produces:
- application/json
schemes:
- http
swagger: "2.0"
